import type { CertificationRec } from "./onboarding-types";

export const DOMAIN_CERTIFICATIONS: Record<string, CertificationRec[]> = {
  "full-stack": [
    {
      name: "Meta Full-Stack Engineer Professional Certificate",
      provider: "Meta",
      description: "Master React, Node.js, Express, databases, and deployment strategies directly from Meta software engineers.",
      difficulty: "Intermediate",
      duration: "6 months (7 hrs/week)",
      url: "https://www.coursera.org/professional-certificates/meta-front-end-developer",
      skills: ["React", "Node.js", "REST APIs", "SQL", "Git"],
      matchScore: 96,
      featured: true,
    },
    {
      name: "AWS Certified Developer – Associate",
      provider: "Amazon Web Services",
      description: "Validate technical expertise in developing, deploying, and debugging cloud-based applications on AWS.",
      difficulty: "Intermediate",
      duration: "3 months",
      url: "https://aws.amazon.com/certification/certified-developer-associate/",
      skills: ["AWS Lambda", "DynamoDB", "ECS", "Serverless", "CI/CD"],
      matchScore: 92,
    },
    {
      name: "OpenJS Node.js Application Developer (JSNAD)",
      provider: "Linux Foundation / OpenJS",
      description: "Official performance-based certification for Node.js application developer proficiency.",
      difficulty: "Advanced",
      duration: "2 months",
      url: "https://training.linuxfoundation.org/certification/jsnad/",
      skills: ["Node.js Core", "Asynchronous Programming", "Security", "REST"],
      matchScore: 88,
    },
  ],
  "frontend": [
    {
      name: "Meta Front-End Developer Professional Certificate",
      provider: "Meta",
      description: "Learn UI engineering, React state management, web accessibility, and UX design from Meta developers.",
      difficulty: "Beginner",
      duration: "5 months",
      url: "https://www.coursera.org/professional-certificates/meta-front-end-developer",
      skills: ["React", "HTML5/CSS3", "JavaScript ES6+", "Figma", "Web Performance"],
      matchScore: 98,
      featured: true,
    },
    {
      name: "W3Cx Frontend Web Developer Professional Certificate",
      provider: "W3C / edX",
      description: "Official W3C certification covering core standards: HTML5, CSS Grid, Flexbox, JavaScript, and accessibility.",
      difficulty: "Beginner",
      duration: "4 months",
      url: "https://www.edx.org/certificates/professional-certificate/w3cx-front-end-web-developer",
      skills: ["W3C Standards", "WCAG Accessibility", "CSS3", "DOM Manipulation"],
      matchScore: 90,
    },
  ],
  "backend": [
    {
      name: "Meta Back-End Developer Professional Certificate",
      provider: "Meta",
      description: "Learn Python, Django, SQL databases, microservices architecture, and cloud deployment.",
      difficulty: "Intermediate",
      duration: "6 months",
      url: "https://www.coursera.org/professional-certificates/meta-back-end-developer",
      skills: ["Python", "Django", "PostgreSQL", "REST APIs", "Docker"],
      matchScore: 97,
      featured: true,
    },
    {
      name: "AWS Certified Developer – Associate",
      provider: "Amazon Web Services",
      description: "Industry gold-standard credential for building microservices, cloud APIs, and database integrations on AWS.",
      difficulty: "Intermediate",
      duration: "3 months",
      url: "https://aws.amazon.com/certification/certified-developer-associate/",
      skills: ["AWS", "DynamoDB", "S3", "API Gateway", "Lambda"],
      matchScore: 94,
    },
    {
      name: "Oracle Certified Professional: Java SE Developer",
      provider: "Oracle",
      description: "Rigorous certification proving deep mastery of Java, OOP, concurrency, and enterprise design patterns.",
      difficulty: "Advanced",
      duration: "4 months",
      url: "https://education.oracle.com/java-se-17-developer/pexam_1Z0-829",
      skills: ["Java SE", "Concurrency", "OOP", "JVM Performance"],
      matchScore: 89,
    },
  ],
  "mobile": [
    {
      name: "Meta Android Developer Professional Certificate",
      provider: "Meta",
      description: "Build Android apps using Kotlin, Jetpack Compose, Android Studio, and RESTful web services.",
      difficulty: "Intermediate",
      duration: "6 months",
      url: "https://www.coursera.org/professional-certificates/meta-android-developer",
      skills: ["Kotlin", "Jetpack Compose", "Android SDK", "REST APIs"],
      matchScore: 96,
      featured: true,
    },
    {
      name: "Meta iOS Developer Professional Certificate",
      provider: "Meta",
      description: "Learn Swift, SwiftUI, Xcode, core graphics, and mobile UX design from Meta iOS engineers.",
      difficulty: "Intermediate",
      duration: "6 months",
      url: "https://www.coursera.org/professional-certificates/meta-ios-developer",
      skills: ["Swift", "SwiftUI", "Xcode", "Core Data", "iOS SDK"],
      matchScore: 95,
    },
  ],
  "ai-engineer": [
    {
      name: "DeepLearning.AI Generative AI & LLM Professional Certificate",
      provider: "DeepLearning.AI",
      description: "Build LLM applications, RAG pipelines, prompt engineering, and fine-tune foundation models with PyTorch.",
      difficulty: "Intermediate",
      duration: "3 months",
      url: "https://www.coursera.org/specializations/generative-ai-engineering-with-llms",
      skills: ["LLMs", "RAG", "LangChain", "PyTorch", "Prompt Engineering"],
      matchScore: 98,
      featured: true,
    },
    {
      name: "AWS Certified Machine Learning – Specialty",
      provider: "Amazon Web Services",
      description: "Design, implement, deploy, and maintain machine learning workloads on SageMaker and AWS cloud.",
      difficulty: "Advanced",
      duration: "4 months",
      url: "https://aws.amazon.com/certification/certified-machine-learning-specialty/",
      skills: ["SageMaker", "MLOps", "Model Deployment", "NLP", "Computer Vision"],
      matchScore: 93,
    },
  ],
  "ml-engineer": [
    {
      name: "DeepLearning.AI Machine Learning Specialization",
      provider: "DeepLearning.AI",
      description: "Master foundational ML concepts: supervised learning, neural networks, decision trees, and reinforcement learning.",
      difficulty: "Beginner",
      duration: "3 months",
      url: "https://www.coursera.org/specializations/machine-learning-introduction",
      skills: ["Python", "NumPy", "Scikit-Learn", "TensorFlow", "Neural Networks"],
      matchScore: 98,
      featured: true,
    },
    {
      name: "TensorFlow Developer Certificate",
      provider: "Google / TensorFlow",
      description: "Official certification proving proficiency in using TensorFlow to solve computer vision, NLP, and time-series problems.",
      difficulty: "Intermediate",
      duration: "2 months",
      url: "https://www.tensorflow.org/certificate",
      skills: ["TensorFlow", "Keras", "Deep Learning", "CNNs", "RNNs"],
      matchScore: 94,
    },
  ],
  "data-scientist": [
    {
      name: "IBM Data Science Professional Certificate",
      provider: "IBM",
      description: "Master Python, SQL, data visualization, predictive modeling, and machine learning algorithms.",
      difficulty: "Beginner",
      duration: "5 months",
      url: "https://www.coursera.org/professional-certificates/ibm-data-science",
      skills: ["Python", "Pandas", "Scikit-Learn", "SQL", "Data Viz"],
      matchScore: 96,
      featured: true,
    },
    {
      name: "Google Cloud Professional Data Engineer",
      provider: "Google Cloud",
      description: "Design data processing systems, machine learning models, and big data pipelines on GCP.",
      difficulty: "Advanced",
      duration: "4 months",
      url: "https://cloud.google.com/learn/certification/data-engineer",
      skills: ["BigQuery", "Dataflow", "Pub/Sub", "Spark", "SQL"],
      matchScore: 92,
    },
  ],
  "data-analyst": [
    {
      name: "Google Data Analytics Professional Certificate",
      provider: "Google",
      description: "Gain hands-on analytical skills with SQL, R programming, Tableau, and data cleaning techniques.",
      difficulty: "Beginner",
      duration: "4 months",
      url: "https://www.coursera.org/professional-certificates/google-data-analytics",
      skills: ["SQL", "R Language", "Tableau", "Data Cleaning", "Data Analysis"],
      matchScore: 97,
      featured: true,
    },
    {
      name: "Microsoft Certified: Power BI Data Analyst Associate",
      provider: "Microsoft",
      description: "Demonstrate expertise in transforming data into actionable insights using Microsoft Power BI dashboards.",
      difficulty: "Intermediate",
      duration: "2 months",
      url: "https://learn.microsoft.com/en-us/credentials/certifications/power-bi-data-analyst-associate/",
      skills: ["Power BI", "DAX", "Data Modeling", "Business Intelligence"],
      matchScore: 91,
    },
  ],
  "cybersecurity": [
    {
      name: "CompTIA Security+ Certification",
      provider: "CompTIA",
      description: "The global benchmark credential for securing networks, devices, threat intelligence, and compliance.",
      difficulty: "Intermediate",
      duration: "3 months",
      url: "https://www.comptia.org/certifications/security",
      skills: ["Threat Hunting", "Cryptography", "Network Security", "Risk Management"],
      matchScore: 98,
      featured: true,
    },
    {
      name: "Certified Information Systems Security Professional (CISSP)",
      provider: "(ISC)²",
      description: "World-renowned security credential proving deep technical & managerial competence in cyber defense.",
      difficulty: "Advanced",
      duration: "6 months",
      url: "https://www.isc2.org/Certifications/CISSP",
      skills: ["Security Architecture", "Asset Security", "Identity & Access", "Risk Management"],
      matchScore: 91,
    },
  ],
  "cloud": [
    {
      name: "AWS Certified Solutions Architect – Associate",
      provider: "Amazon Web Services",
      description: "Demonstrate high-level knowledge of designing resilient, high-performing, secure cloud architectures.",
      difficulty: "Intermediate",
      duration: "3 months",
      url: "https://aws.amazon.com/certification/certified-solutions-architect-associate/",
      skills: ["VPC", "EC2", "S3", "CloudFront", "IAM", "Auto Scaling"],
      matchScore: 98,
      featured: true,
    },
    {
      name: "Google Cloud Associate Cloud Engineer",
      provider: "Google Cloud",
      description: "Deploy applications, monitor operations, and manage enterprise solutions on Google Cloud Platform.",
      difficulty: "Beginner",
      duration: "2 months",
      url: "https://cloud.google.com/learn/certification/cloud-engineer",
      skills: ["GCP", "GKE", "Cloud Run", "IAM", "BigQuery"],
      matchScore: 92,
    },
    {
      name: "Microsoft Certified: Azure Fundamentals (AZ-900)",
      provider: "Microsoft",
      description: "Foundational knowledge of cloud concepts, Azure services, security, privacy, and compliance.",
      difficulty: "Beginner",
      duration: "1 month",
      url: "https://learn.microsoft.com/en-us/credentials/certifications/azure-fundamentals/",
      skills: ["Azure Core Services", "Cloud Governance", "Security"],
      matchScore: 88,
    },
  ],
  "devops": [
    {
      name: "Certified Kubernetes Administrator (CKA)",
      provider: "Linux Foundation / CNCF",
      description: "The premier performance-based exam proving skill in Kubernetes installation, configuration, and management.",
      difficulty: "Advanced",
      duration: "3 months",
      url: "https://training.linuxfoundation.org/certification/certified-kubernetes-administrator-cka/",
      skills: ["Kubernetes", "Container Orchestration", "Networking", "Cluster Security"],
      matchScore: 97,
      featured: true,
    },
    {
      name: "HashiCorp Certified: Terraform Associate",
      provider: "HashiCorp",
      description: "Validate understanding of Infrastructure as Code concepts and hands-on proficiency with Terraform CLI.",
      difficulty: "Intermediate",
      duration: "2 months",
      url: "https://www.hashicorp.com/certification/terraform-associate",
      skills: ["Terraform", "Infrastructure as Code", "Cloud Automation", "HCL"],
      matchScore: 93,
    },
  ],
  "ui-ux": [
    {
      name: "Google UX Design Professional Certificate",
      provider: "Google",
      description: "Learn wireframing, prototyping, user research, usability testing, and Figma design systems.",
      difficulty: "Beginner",
      duration: "6 months",
      url: "https://www.coursera.org/professional-certificates/google-ux-design",
      skills: ["Figma", "User Research", "Wireframing", "Prototyping", "Design Systems"],
      matchScore: 98,
      featured: true,
    },
    {
      name: "UI / UX Design Specialization by CalArts",
      provider: "California Institute of the Arts",
      description: "Comprehensive visual and interaction design training covering screen design, typography, and user research.",
      difficulty: "Intermediate",
      duration: "4 months",
      url: "https://www.coursera.org/specializations/graphic-design",
      skills: ["Visual Design", "Typography", "Interface Design", "User Journeys"],
      matchScore: 90,
    },
  ],
  "software-engineer": [
    {
      name: "Meta Full-Stack Engineer Professional Certificate",
      provider: "Meta",
      description: "Software engineering fundamentals: data structures, web development, cloud backends, and databases.",
      difficulty: "Intermediate",
      duration: "6 months",
      url: "https://www.coursera.org/professional-certificates/meta-front-end-developer",
      skills: ["Software Engineering", "Algorithms", "React", "Node.js", "System Design"],
      matchScore: 96,
      featured: true,
    },
    {
      name: "AWS Certified Developer – Associate",
      provider: "Amazon Web Services",
      description: "Validate technical expertise in developing, deploying, and debugging software systems on AWS.",
      difficulty: "Intermediate",
      duration: "3 months",
      url: "https://aws.amazon.com/certification/certified-developer-associate/",
      skills: ["AWS", "Microservices", "Cloud Architecture", "CI/CD"],
      matchScore: 92,
    },
  ],
  "blockchain": [
    {
      name: "Certified Ethereum Developer",
      provider: "Linux Foundation / BTA",
      description: "Master Solidity, smart contract security, Web3.js, EVM architecture, and decentralized app deployment.",
      difficulty: "Advanced",
      duration: "3 months",
      url: "https://training.linuxfoundation.org/",
      skills: ["Solidity", "Ethereum", "Smart Contracts", "Web3.js", "Hardhat"],
      matchScore: 95,
      featured: true,
    },
  ],
  "embedded": [
    {
      name: "Linux Foundation Embedded Linux Development",
      provider: "Linux Foundation",
      description: "Master C programming, kernel drivers, RTOS, microcontrollers, and embedded system architecture.",
      difficulty: "Advanced",
      duration: "4 months",
      url: "https://training.linuxfoundation.org/training/embedded-linux-development/",
      skills: ["C/C++", "Embedded Linux", "RTOS", "Kernel Drivers", "Microcontrollers"],
      matchScore: 96,
      featured: true,
    },
  ],
  "game-dev": [
    {
      name: "Unity Certified Associate Game Developer",
      provider: "Unity Technologies",
      description: "Validate core game programming skills in C#, Unity 3D engine, gameplay mechanics, and physics.",
      difficulty: "Intermediate",
      duration: "3 months",
      url: "https://unity.com/learn/certification",
      skills: ["Unity 3D", "C#", "Game Physics", "3D Graphics", "Asset Management"],
      matchScore: 97,
      featured: true,
    },
  ],
  "ar-vr": [
    {
      name: "Unity Certified VR Developer",
      provider: "Unity Technologies",
      description: "Build immersive virtual reality and augmented reality experiences using Unity, OpenXR, and spatial 3D audio.",
      difficulty: "Advanced",
      duration: "4 months",
      url: "https://unity.com/learn/certification",
      skills: ["Unity VR", "OpenXR", "3D Modeling", "Spatial Audio", "C#"],
      matchScore: 96,
      featured: true,
    },
  ],
};

export function getRecommendedCertifications(domainId?: string | null): CertificationRec[] {
  if (!domainId) return DOMAIN_CERTIFICATIONS["full-stack"]!;
  const key = domainId.toLowerCase().trim().replace(/\s+/g, "-");
  if (DOMAIN_CERTIFICATIONS[key]) return DOMAIN_CERTIFICATIONS[key]!;

  // Fuzzy match domain key
  const match = Object.keys(DOMAIN_CERTIFICATIONS).find((k) => key.includes(k) || k.includes(key));
  if (match && DOMAIN_CERTIFICATIONS[match]) return DOMAIN_CERTIFICATIONS[match]!;

  return DOMAIN_CERTIFICATIONS["full-stack"]!;
}
